if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    if(SANITIZE STREQUAL "Address")
        set(SANITIZERS "address,leak")
    elseif(SANITIZE STREQUAL "Memory")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            set(SANITIZERS "memory")
        else()
            message(FATAL_ERROR "Memory sanitizer is not available for ${CMAKE_CXX_COMPILER_ID}")
        endif()
    elseif(SANITIZE STREQUAL "Thread")
        set(SANITIZERS "thread")
    elseif(SANITIZE)
        message(FATAL_ERROR "Unknown sanitizer ${SANITIZE}")
    endif()

    if(SANITIZERS)
        add_compile_options("-fsanitize=${SANITIZERS}")
        add_link_options("-fsanitize=${SANITIZERS}")
    endif()
endif()
