name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test application
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
        compiler:
          - [g++, g++]
          # temporarily disabled clang as builds hang on GitHub for some reason
          # - [clang, clang++]
        build-type:
          - Debug
          - Release
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends git cmake make ${{ matrix.compiler[0] }}
          libcurl4-openssl-dev libuv1-dev zlib1g-dev libjpeg-turbo8-dev
      - uses: actions/cache@v3
        with:
          path: ./build
          key: ${{matrix.os}}-${{matrix.compiler[0]}}-${{matrix.build-type}}
      - name: Setup CMake
        run:
          CXX=${{matrix.compiler[1]}} cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type}}
          -DUSE_CLANG_FORMAT=OFF -DUSE_CLANG_TIDY=OFF -DUSE_IWYU=OFF -DUSE_DOXYGEN=OFF
      - name: Build
        run: cmake --build build --config ${{ matrix.build-type}} --parallel $(nproc)
      - name: Test
        run: cd ./build && ctest
